language: ruby
sudo: false
cache: bundler
rvm:
  - 2.5.3
  - 2.6.1
before_install:
  - gem update --system
gemfile:
  - gemfiles/rails_4.2.11.1.gemfile
  - gemfiles/rails_5.0.7.2.gemfile
  - gemfiles/rails_5.1.6.2.gemfile
  - gemfiles/rails_5.2.2.1.gemfile
  - gemfiles/rails_6.0.0.beta3.gemfile
