language: ruby
sudo: false
cache: bundler
rvm:
  - 2.3.1
  - 2.2.5
gemfile:
  - gemfiles/rails_5.gemfile
  - gemfiles/rails_4.gemfile

script: 'bundle exec rake'

notifications:
  email:
    recipients:
      - felipe@29sul.com.br
      - elton@29sul.com.br
    on_failure: change # [always|never|change]
    on_success: change # [always|never|change]
